### ISSUE TITLE
email notification

### ISSUE THREAD

**Issue by ntimo** [plesk/ext-website-virus-check#2]
Hi there,

could you please implement a email notification system? Even if the mail may not reach my inbox its worth the try I think. And I never had any problems with my plesk server sending me emails.

Thank you
Timo

**Comment by ntimo** [comment]
Can you give an estimate when the feature will be will be available :) Can't wait for it. 

Thank you, 
for implementing it.

**Comment by vlikhtanskiy** [comment]
The new version has been published: https://ext.plesk.com/packages/24e15804-3134-4561-a2a2-1bdc7228e98f-website-virus-check

**Comment by oneumyvakin** [comment]
You can found "Upgrade" button near "VirusTotal WebSite Check" in Plesk extension catalog page.
After upgrade there new setting "Email notification" on Settings tab.
Implementation is straight forward - one notification per "bad" domain in a day.
