### ISSUE TITLE
Website virus check and Cloudflare

### ISSUE THREAD

**Issue by pkeizer** [plesk/ext-website-virus-check#21]
On our (Plesk/CentOs) server I installed VirusTotal Website Check.
The problem is that VirusTotal can not scan the websites on the server. I get the following error for each website: 
'Domain is "Suspended", "Disabled" or can't be resolved in hosting IP address'.

In the Plesk log I see the following error:

'[2017-05-05 13:01:31] ERR [extension/website-virus-check] Failed to request GET https://www.virustotal.com/vtapi/v2/url/scanRead timed out after 10 seconds'

All the website are added to Cloudflare and I suspect that is the reason
That VirusTotal can not scan the websites.
Could you solve this issue?

**Comment by oneumyvakin** [comment]
Thanks for the issue! 

Yes, Cloudflare may be the reason of message 'Domain is "Suspended", "Disabled" or can't be resolved in hosting IP address'  

Think we can make this behaviour optional in next release.

**Comment by pkeizer** [comment]
Thanks for your reply.
Do you know when the next release will be?

**Comment by oneumyvakin** [comment]
Well, this extension has no exact roadmap or release plan. 
Currently I've planned to add one major feature in next release and it will takes time. 
So 1-2 months will be fair answer.

**Comment by pkeizer** [comment]
Fair enough.
I look forward to the next release.

**Comment by oneumyvakin** [comment]
New option "Disable Domain Resolving" is added in version v.1.4-1. Upgrade should be available in Extensions in Plesk.

p.s.: no major feature in this release
